fourth_project/fourth_app/urls.py
from django.conf.urls import url
from fourth_app import views

app_name = 'fourth_app'
urlpatterns = [
    url(r'^$', views.index, name='other'),
    url(r'^other/$', views.other, name='other'),
    url(r'^relative/$', views.relative, name='relative'),
]

fourth_project/fourth_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from fourth_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^fourth_app/', include('fourth_app.urls')),
    url(r'^admin/', admin.site.urls),
]

fourth_project/fourth_app/models.py
from django.db import models

# Create your models here.

fourth_project/fourth_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world', 'number': 100}
    return render(request, 'fourth_app/index.html', context_dict)

def other(request):
    return render(request, 'fourth_app/other.html')

def relative(request):
    return render(request, 'fourth_app/relative_url_templates.html')

fourth_project/templates/fourth_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <a class="nav-brand" href="{% url 'index' %}">Brand</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'fourth_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

fourth_project/templates/fourth_app/index.html
<!DOCTYPE html>
{% extends "fourth_app/base.html" %}
  {% load fourth_app_extras %}
  {% block body_block %}
  <h1>Welcome to Index!</h1>
  <!-- <h1>This is index.html page showing!</h1> -->
  <h1>{{ text|cutting:"hello" }}</h1>
  <h1>{{ number|add:"99" }}</h1>
  {% endblock %}

fourth_project/templates/fourth_app/other.html
<!DOCTYPE html>
{% extends "fourth_app/base.html" %}
  {% block body_block %}
  <h1>Welcome to Other!</h1>
  <h2>This is an example of template inheritance</h2>
  {% endblock %}

fourth_project/templates/fourth_app/relative_url_templates.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative Url Templates!</h1>
    <a href="{% url 'fourth_app:relative' %}">Relative</a>
    <a href="{% url 'fourth_app:other' %}">Other</a>

    <a href="{% url 'admin:index' %}">Admin Index</a>
    <a href="{% url 'index' %}">Index</a>
  </body>
</html>