fifth_project/fifth_app/urls.py
from django.conf.urls import url
from fifth_app import views

app_name = 'fifth_app'
urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
]

fifth_project/fifth_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from fifth_app import views as fifth_app_views

urlpatterns = [
    url(r'^$', fifth_app_views.index, name='index'),
    url(r'^fifth_app/', include('fifth_app.urls')),
    url(r'^admin/', admin.site.urls),
]

fifth_project/fifth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):

    user = models.OneToOneField(User)

    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

fifth_project/fifth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from fifth_app.models import UserProfile

class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture', 'portfolio',)

fifth_project/fifth_app/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from fifth_app.forms import UserForm, UserProfileForm

# Create your views here.
def index(request):
    return render(request, 'fifth_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Account not Active')
        else:
            print ("Someone tried to login and failed {username: {}, password: {}}".format(username, password))

            return HttpResponse('Invalid login details supplied!')
    else:
        return render(request, 'fifth_app/login.html')


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    params = {'user_form': user_form, 'profile_form': profile_form, 'registered': registered}

    return render(request, 'fifth_app/registration.html', params)

fifth_project/templates/fifth_app/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if not user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'fifth_app:register' %}">Register</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>

          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'fifth_app:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'fifth_app:user_login' %}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

    <div>
      {{ user.name }}
    </div>
  </body>
</html>

fifth_project/templates/fifth_app/index.html
{% extends "fifth_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django Level Five</h1>
  </div>
{% endblock %}

fifth_project/templates/fifth_app/login.html
{% extends "fifth_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'fifth_app:user_login' %}" method="POST">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username" />

      <label for="password">Password:</label>
      <input type="password" name="password" placeholder="Enter Password" />

      <input type="submit" value="Login" />
    </form>
  </div>
{% endblock %}

fifth_project/templates/fifth_app/registration.html
{% extends "fifth_app/base.html" %}
{% load staticfiles %}

{% block body_block %}
<div class="jumbotron">
  {% if registered %}
  <h1>Thank you for registering!</h1>
  {% else %}
  <h1>Register Here!</h1>
  <h3>Fill out the form:</h3>

  <form method="POST" enctype="multipart/form-data">
    <table>
    {{ user_form.as_table }}
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    {{ profile_form.as_table }}
    </table>
    {% csrf_token %}
    <input type="submit" value="Send" />
  </form>
  {% endif %}
</div>
{% endblock %}